# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitLos < Formula
  desc "Git LFS custom transfer agent with native GCS and S3 support"
  homepage "https://github.com/valent-au/git-los"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/valent-au/git-los/releases/download/v0.1.0/git-los_0.1.0_darwin_x86_64.tar.gz"
      sha256 "379f894d0d5bfafafe0282a4f524f6d131058b880d24e86d9218396a20fcaa44"

      def install
        bin.install "git-los"
      end
    end
    on_arm do
      url "https://github.com/valent-au/git-los/releases/download/v0.1.0/git-los_0.1.0_darwin_arm64.tar.gz"
      sha256 "92185364fb12f3f4d133e66e2c42d71fd2948317c82030927e7360a0d912ac95"

      def install
        bin.install "git-los"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/valent-au/git-los/releases/download/v0.1.0/git-los_0.1.0_linux_x86_64.tar.gz"
        sha256 "83e618db61c16715cafe945366b7387e21643a8d3c47db7a18a8fc81cb4eb474"

        def install
          bin.install "git-los"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/valent-au/git-los/releases/download/v0.1.0/git-los_0.1.0_linux_arm64.tar.gz"
        sha256 "02f08597dc7a8023a9d6068d981e73c38cf0fde7adb3aca082d4b22d843474c2"

        def install
          bin.install "git-los"
        end
      end
    end
  end

  test do
    system "#{bin}/git-los", "version"
  end
end
